version: '3.7'
services:
  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gas
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data/pgdata
volumes:
  postgres_db:
